<?php
declare(strict_types=1);

/**
 * This file is part of Awooing.moe
 */

namespace App\Presenters;

use Nette;
use Awoo\Models\MainModel;
use Nette\Application\AbortException;
use Nette\Database\Context;

class AdminPresenter extends BasePresenter
{
    /** @var Context */
    private $database;

    /** @var MainModel */
    private $model;

    /**
     * AdminPresenter constructor.
     * @param Context $db
     * @param MainModel $model
     */
    public function __construct(Context $db, MainModel $model)
    {
        parent::__construct($db, $model);
        $this->database = $db;
        $this->model = $model;
    }

    /**
     * Startup method which checks
     * if user is logged in and allowed to view the admin panel.
     * @throws AbortException
     */
    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        if (!$this->getUser()->isLoggedIn()) {
            $this->flashMessage("<script id='41458148941125_denied'>Swal.fire({title: 'Access Denied', content: 'You don\'t have access to this site.', icon:'error', showConfirmButton: false, timer: 1000, timerProgressBar: true});$('#41458148941125_denied').remove();</script>", "script");
            $this->redirect("Homepage:");
        }
        if (!$this->getUser()->isAllowed("admin", "view")) {
            $this->flashMessage("<script id='41458148941125_denied'>Swal.fire({title: 'Access Denied', content: 'You don\'t have access to this site.', icon:'error', showConfirmButton: false, timer: 1000, timerProgressBar: true});$('#41458148941125_denied').remove();</script>", "script");
            $this->redirect("Homepage:");
        }
    }

}