<?php
declare(strict_types=1);
namespace Awoo\OAuth\Flow;

use Contributte\OAuth2Client\Exception\Runtime\UserProbablyDeniedAccessException;
use Contributte\OAuth2Client\Flow\AuthCodeFlow;
use League\OAuth2\Client\Provider\AbstractProvider;
use League\OAuth2\Client\Token\AccessTokenInterface;
use Nette\Application\BadRequestException;
use Nette\Application\UI\Presenter;
use Nette\Http\Session;
use Wohali\OAuth2\Client\Provider\Discord;
use Wohali\OAuth2\Client\Provider\Exception\DiscordIdentityProviderException;

/**
 * @method Discord getProvider()
 */
class DiscordAuthCodeFlow extends AuthCodeFlow
{
    public function __construct(Discord $provider, Session $session)
    {
        parent::__construct($provider, $session);
    }

    /**
     * @param array $parameters
     * @return AccessTokenInterface
     * @throws DiscordIdentityProviderException
     * @throws \League\OAuth2\Client\Provider\Exception\IdentityProviderException
     */
    public function getAccessToken(array $parameters): AccessTokenInterface
    {
        if (isset($parameters['error'])) {
            throw new UserProbablyDeniedAccessException($parameters['error']);
        }
        try {
            $token = parent::getAccessToken($parameters); // TODO: Change the autogenerated stub
        } catch (DiscordIdentityProviderException $e) {
            throw $e;
        }
        return $token;
    }

}